# Generated by Django 5.1.1 on 2024-10-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_sepehr',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
